export interface WordCategory {
  id: string;
  name: string;
  tagalog: string;
  words: string[];
}

export const categories: WordCategory[] = [
  {
    id: "easy",
    name: "Easy Words",
    tagalog: "Madaling Salita",
    words: [
      "bahay", "aso", "pusa", "manok", "baboy", "baka", "tupa", "kambing",
      "isda", "ibon", "buwaya", "tigre", "leon", "elepante", "unggoy",
      "saging", "mansanas", "kamatis", "sibuyas", "bawang", "luya", "sili",
      "pipino", "kalabasa", "talong", "repolyo", "pechay", "sitaw", "mais",
      "bigas", "tinapay", "kape", "gatas", "tubig", "sabaw", "kanin",
      "tinola", "sinigang", "adobo", "kare-kare", "lechon", "halo-halo",
      "leche flan", "biko", "suman", "puto", "kakanin", "bibingka",
      "tsokolate", "kendi", "peras", "ubas", "pakwan", "pinya", "calamansi",
      "niyog", "bayabas", "mangga", "lanzones", "chico", "atis", "rambutan",
      "lansones", "mangosteen", "dalandan", "santol", "siniguelas", "damo",
      "puno", "bulaklak", "dahon", "ugat", "buto", "balat", "buhok",
      "mata", "baba", "ilong", "tainga", "ngipin", "dila", "leeg", "balikat",
      "braso", "kamay", "daliri", "kuko", "tiyan", "likod", "tuwid",
      "binti", "paa", "talon", "takbo", "lakad", "upo", "higa", "tayo",
      "kain", "inom", "tulog", "gising", "laro", "tawa", "iyak", "sigaw",
      "huni", "kanta", "sayaw", "sulat", "basa", "kwento", "kuwento",
    ],
  },
  {
    id: "pagkain",
    name: "Food",
    tagalog: "Pagkain",
    words: [
      "sinigang", "adobo", "kare-kare", "lechon", "sisig", "kansi", "bopis",
      "dinuguan", "pinakbet", "laing", "ginataan", "tinola", "nilaga", "pesang",
      "bulalo", "kaldereta", "mechado", "pochero", "menudo", "afritada",
      "ginisang", "pritong", "inihaw",
      "sinangag", "bagoong", "patis", "sawsawan", "kamatis", "sibuyas", "bawang",
      "luya", "siling", "sili", "paminta", "asin", "asukal", "suka",
      "mantika", "toyo", "sarsa", "ketsap", "mayonesa",
      "mustasa", "mani", "pulot", "mantikilya", "margarina",
      "keso", "crema", "gatas", "evaporada", "condensada",
      "kape", "tsaa", "tsokolate", "jus", "serbesa",
      "alak", "tubig", "halo-halo", "taho", "balut", "penoy", "kwek-kwek", "fishball",
      "lumpia", "siomai", "siopao",
      "mami", "miswa", "pancit", "pancit canton", "pancit bihon",
      "sotanghon", "bihon", "sopas",
    ],
  },
  {
    id: "hayop",
    name: "Animals",
    tagalog: "Hayop",
    words: [
      "aso", "pusa", "baboy", "baka", "kambing", "tupa", "kabayo",
      "manok", "itik", "gansa", "pato", "kalapati", "maya", "uwak",
      "agila", "paru-paro", "tutubi", "langgam", "gamu-gamo", "daga",
      "alakdan", "butiki", "ahas", "buwaya", "pagong", "higad", "gagamba",
      "sintakas", "tipaklong", "isda", "hipon", "alimasag", "pusit",
      "pugita", "dolpon", "balyena", "pating",
      "pagong", "dambuhalang", "leon", "tigre",
      "elepante", "kiraf", "sinuparintas", "hipopotamus", "gorilya",
      "unggoy", "oso", "lobeong", "soro",
      "kuneho", "hamster", "dambuhalang daga", "gerbil",
      "usa", "elk", "moose", "carabao", "kalabaw", "tarsier",
      "muskang", "civet cat", "palm civet", "bayawak",
      "tuko", "gecko", "palaka", "palakang bukid",
      "tilaok ng manok", "ugong ng aso",
      "tunog ng pusa", "ingay ng baboy",
    ],
  },
  {
    id: "trabaho",
    name: "Jobs",
    tagalog: "Trabaho",
    words: [
      "doktor", "nars", "pulis", "sundalo", "guro", "manunulat", "artista",
      "abogado", "inhinyero", "arkitekto", "mananaliksik",
      "mananahi", "karpintero", "mason", "mekaniko", "bumbero",
      "tagaluto", "tagapagluto", "manunulat",
      "sekretaryo", "manedyer", "amo",
      "presidente", "mayor", "gobernador", "senador", "kongresista",
      "hukom", "dentista", "beterinaryo",
      "oditor", "tagapagmana", "tagapagbilang",
      "vendor", "tindero", "tindera", "magsasaka", "mangingisda",
      "pastol", "bantay", "seguridad", "tagalinis",
      "driver ng bus", "driver ng tricycle", "driver ng jeepney",
      "tagahatid ng sulat", "tagapagdeliver",
      "mamamahayag", "tagapagbalita",
      "tagapaglaro", "coach", "referee",
      "mang-aawit", "mananayaw", "musiko", "pintor", "eskultor",
      "tagapagluto ng tinapay", "pumatay ng karne", "florista", "hardinero",
    ],
  },
  {
    id: "lugar",
    name: "Places",
    tagalog: "Lugar",
    words: [
      "bahay", "opisina", "eskwela", "universidad", "ospital", "simbahan",
      "mall", "palengke", "tiangge", "tindahan", "talyer", "gasolinahan",
      "bangko", "parke", "laruan",
      "stadium", "arena", "gym", "dalampasigan",
      "bundok", "bulkan", "ilog", "talampasan", "kapatagan",
      "gubat", "lawa", "dagat-dagatan", "ilog Pasig",
      "Maynila", "Quezon City", "Cebu", "Davao", "Baguio", "Tagaytay",
      "Palawan", "Boracay", "Siargao", "Bohol", "Vigan", "Coron",
      "El Nido", "Moalboal", "Oslob", "Apo Island", "Sumilon",
      "klinika", "laboratoryo", "botika",
      "terminal", "paliparan", "daungan", "istasyon",
      "hintayan ng bus", "terminal ng jeep",
      "pasilyo", "elevator", "hagdanan", "bubong",
      "basement", "garahe", "likod-bahay", "harap-bahay", "hardin",
      "kusina", "kwarto", "banyo", "sala", "kainan",
      "teresa", "balkonahe", "patyo", "veranda",
    ],
  },
  {
    id: "entertainment",
    name: "Entertainment",
    tagalog: "Entertainment",
    words: [
      "konsiyerto", "pista", "fiesta", "parada", "pagdiriwang",
      "karaoke", "videoke",
      "sinehan", "teatro", "museo",
      "galeriya", "exhibit", "perya", "carnival", "sirkus",
      "show ng magic", "komedyi show", "talent show",
      "game show", "reality show", "talk show",
      "teleserye", "teleserye", "soap opera", "anime", "karton",
      "drama", "horror", "komedyi", "aksyon", "romansa",
      "siyensya", "fantasya", "dokumentaryo", "musikal", "ballet",
      "opera", "orkestra", "banda", "rock concert", "akustik",
      "rapper", "mang-aawit", "kanta", "album",
      "podcast", "vlog", "blog", "social media",
      "gaming", "e-sports", "Minecraft", "Roblox", "Fortnite",
    ],
  },
  {
    id: "pasko",
    name: "Christmas",
    tagalog: "Pasko",
    words: [
      "Pasko", "Noche Buena", "Simbang Gabi", "Misa de Gallo",
      "parol", "puno ng Pasko", "belen",
      "regalo", "balot-regalo", "papel de balot",
      "guirlanda", "busbos",
      "awit ng Pasko", "caroling",
      "Bisperas ng Pasko", "Bagong Taon", "Bisperas", "Media Noche",
      "paputok", "torotot",
      "salu-salo", "handaan",
      "bibingka", "puto bumbong", "leche flan",
      "hamon", "kasuy", "pastillas", "polvoron",
      "ensaymada", "pan de sal", "tsokolate",
      "mga bulaklak", "anghel", "bituin",
    ],
  },
  {
    id: "bituin",
    name: "Celebrities",
    tagalog: "Bituin",
    words: [
      "Manny Pacquiao", "Pacquiao", "boxing champion", "Senator Pacquiao",
      "John Lloyd Cruz", "John Lloyd", "Kathryn Bernardo", "Kathryn",
      "Daniel Padilla", "Daniel", "James Reid", "Nadine Lustre",
      "Vice Ganda", "Vice", "Willie Revillame", "Willie",
      "Tito Sotto", "Vic Sotto", "Joey de Leon", "Eat Bulaga",
      "Sarah Geronimo", "Sarah G", "Regine Velasquez", "Regine",
      "Aga Muhlach", "Aga", "Piolo Pascual", "Piolo",
      "Heart Evangelista", "Heart", "Marian Rivera", "Dingdong Dantes",
      "Dingdong", "Jennylyn Mercado", "Mark Herras", "Kim Chiu",
      "Gerald Anderson", "Gerald", "Enchong Dee", "Enchong",
      "Liza Soberano", "Liza", "Carlos Agassi", "Aljur Abrenica",
      "Kapamilya", "Kapuso", "Kap Network", "ABS-CBN", "GMA",
      "Showtime", "It's Showtime", "Wowowin", "ASAP", "Sunday PinaSaya",
      "FPJ's Ang Probinsyano", "Ang Probinsyano", "Darna", "Encantadia",
      "Mara Clara", "Pangako Sa'yo", "La Luna Sangre", "The Killer Bride",
      "idol", "star", "artista", "celebrity", "famous", "sikat",
      "crush", "idol ko", "gwapo", "maganda", "guwapo", "sexy",
      "fashion", "outfit", "dress", "suit", "gown", "costume",
    ],
  },
  {
    id: "pag-ibig",
    name: "Love & Dating",
    tagalog: "Pag-ibig at Appointment",
    words: [
      "pag-ibig", "gusto", "mahal",
      "jowa", "jowa ko", "asawa",
      "mister", "misis", "kapareha",
      "date night", "unang date", "blind date",
      "kilig", "kilig na kilig", "tibok ng puso", "puso",
      "liham ng pag-ibig", "awit ng pag-ibig", "kwento ng pag-ibig",
      "pakailanman", "magkasama", "kalahating puso", "tadhana",
      "harana", "kundiman", "liham", "bulong",
      "magkahawak-kamay", "yakap",
      "halik", "mga halik",
      "hiwalay", "wasak ang puso", "sawi", "hugot", "hugot lines",
      "nagseselos", "manloloko", "panloloko", "sinungaling",
      "katotohanan", "hamon",
      "kasal", "pagtatanim", "panliligaw", "manligaw",
      "singsing ng kasal", "singsing na diamante",
      "anibersaryo", "Araw ng mga Puso",
      "mga bulaklak", "mga rosas", "mga pulang rosas",
      "mga tsokolate", "teddy bear",
    ],
  },
  {
    id: "internet",
    name: "Internet Culture",
    tagalog: "Internet at Kultura",
    words: [
      "meme", "viral", "naka-trend", "hashtag", "retweet", "ibahagi",
      "komento", "sundan", "i-unfollow", "i-block", "i-mute",
      "DM", "direktang mensahe", "reply", "thread", "post", "status",
      "kwento", "reels",
      "hamon", "sayaw hamon", "selfie", "groufie",
      "laro", "manlalaro", "streamer", "influencer", "content creator",
      "troll", "manloloko", "hater", "cyberbullying",
      "hacker", "pandaraya", "scammer", "scam",
      "online", "offline", "lag", "buffering", "loading",
      "Wi-Fi", "internet", "data", "cellular", "signal",
      "baterya", "lowbatt", "charger", "power bank",
      "password", "username", "login", "logout",
      "account", "profile", "avatar", "bio",
      "emoji", "sticker", "GIF",
      "unboxing", "ASMR", "mukbang", "vlog", "collab",
    ],
  },
  {
    id: "retro",
    name: "Retro",
    tagalog: "Retro",
    words: [
      "kaset tape", "kaset", "walkman", "Discman", "vinyl",
      "record player", "turntable", "boombox", "radyo", "transistor radio",
      "rotary phone", "telepono", "payphone", "telepono",
      "typewriter", "fax machine", "pager", "beeper", "cellphone",
      "Nokia", "Game Boy", "Famicom", "SEGA", "Atari",
      "Pac-Man", "Super Mario", "Donkey Kong", "Tetris",
      "pixel", "cartridge", "joystick",
      "arcade", "laro ng video", "console ng laro",
      "VHS", "VCR", "Betamax", "laser disc", "DVD player",
      "black and white TV", "CRT TV", "antena", "TV antenna",
      "polaroid", "film camera", "Kodak", "flash bulb", "darkroom",
      "rubber shoes", "Converse", "high top",
      "bell-bottom", "disco", "platform shoes",
      "gold chain", "leather jacket", "denim jacket",
      "neon", "glow stick", "rubik's cube", "slap bracelet", "pogs",
      "luksong tinik", "patintero", "tumbang preso",
      "sungka", "tatsulok", "Chinese garter", "taguan",
    ],
  },
  {
    id: "sports",
    name: "Sports",
    tagalog: "Palakasan",
    words: [
      "basketball", "baseball", "football", "tennis",
      "badminton", "volleyball", "langoy", "boxing", "Manny Pacquiao",
      "track and field", "marathon", "takbo", "bisikleta",
      "gymnastics", "skating", "skiing", "surfing", "skateboarding",
      "ches", "checkers", "laro ng baraha", "poker",
      "Olympics", "FIBA", "FIFA", "World Cup", "campeonato",
      "tornamento", "liga", "season", "playoffs", "finals",
      "MVP", "campeon", "nanalo", "pangalawa", "medalya",
      "gintong medalya", "pilak na medalya", "tansong medalya", "trophy", "trophyo",
      "koponan", "coach", "manlalaro", "referee",
      "jersey", "uniporme", "sneakers",
      "whistle", "scoreboard", "net", "goal", "basket",
      "pitcher", "batter", "catcher", "dribble",
      "pasa", "dunk", "three pointer", "free throw",
      "serve", "volley", "spike",
      "sprint", "hurdle", "relay", "javelin",
      "wrestling", "judo", "karate", "taekwondo", "fencing",
    ],
  },
  {
    id: "medisina",
    name: "Health & Medicine",
    tagalog: "Kalusugan at Medisina",
    words: [
      "doktor", "nars", "ospital", "klinika",
      "sakit", "lagnat", "ubo", "sipon", "trangkaso",
      "tiyan sakit", "allergy", "pantal", "hika",
      "diabetes", "altapresyon", "kanser", "bukol",
      "pagtitistis", "transplant", "chemotherapy",
      "ambulansya", "emergency", "first aid", "CRT", "balot",
      "gamot", "pills", "tablet", "capsule", "syrup",
      "injeksiyon", "bakuna", "booster",
      "mask", "face mask", "alcohol",
      "termometer", "blood pressure", "stethoscope",
      "reseta", "laboratoryo", "pagsusuri",
      "kalusugan", "ehersisyo", "diet", "nutrisyon",
      "protina", "bitamina", "mineral", "calcium",
      "tulog", "pahinga", "pagrerelax", "meditasyon", "yoga",
      "kalusugang pangkaisipan", "stress", "pagkabalisa", "depresyon", "terapiya",
    ],
  },
  {
    id: "musika",
    name: "Music",
    tagalog: "Musika",
    words: [
      "gitara", "piyano", "drum", "biyolin", "flute",
      "trumpeta", "saksophone", "gitara", "keyboard", "organ",
      "ukulele", "harmonika", "accordion", "selo", "banjo",
      "rock", "pop", "jazz", "blues",
      "hip hop", "rap", "reggae",
      "klasikal", "opera", "folk",
      "tekniko", "house",
      "banda", "mang-aawit", "manunulat ng kanta", "kompositor", "musiko",
      "konsiyerto", "gig", "recital", "jam session", "ensayo",
      "album", "playlist",
      "melody", "armoniya", "ritmo", "tempo", "beats",
      "koros", "boses", "tulay", "intro", "outro",
      "lyrics", "mga salita", "mga nota", "chord", "scale",
      "karaoke", "sabay-sabay kumanta", "musical na video",
      "tawag ng tanghalan",
      "OPM", "Pinoy music", "awit ng Pasko",
    ],
  },
  {
    id: "pelikula",
    name: "Movies",
    tagalog: "Pelikula",
    words: [
      "pelikula", "sinehan", "direktor", "skrip", "dialogo",
      "eksena", "eksena", "aksyon", "putol",
      "kamera", "ilaw", "tunog", "pag-eedit",
      "aksyon", "komedyi", "horror", "romansa", "drama",
      "thriller", "misteryo", "siyensya", "fantasya", "animasyon",
      "cartoon", "dokumentaryo", "bograpiya", "musikal",
      "superhero", "Darna", "Encantadia",
      "Ang Probinsyano", "Mara Clara", "Pangako Sa'yo",
      "Netflix", "streaming",
      "sinehan", "popkorn", "soda", "tiket ng sine",
      "blockbuster", "hit", "flop", "sequel", "prequel",
      "trailer", "poster", "reparto", "mga tauhan",
      "aktor", "aktres", "lead role", "cameo",
      "red carpet", "premyere", "film festival",
      "horror movie", "takot", "sigaw", "nakakatakot", "multo",
    ],
  },
  {
    id: "kasanayan",
    name: "Hobbies",
    tagalog: "Kasanayan",
    words: [
      "pagpipinta", "pagdrowing", "pagsasanay", "calligraphy", "palayok",
      "pag-ukit", "paggawa", "pagtatahi", "pag-embrodierya",
      "pag-aalaga ng halaman", "pagtatanim", "pagsasaka", "pag-compost",
      "pagluluto", "pagbe-bake", "pag-iihaw", "barbekyu",
      "pangingisda", "pangangaso", "camping", "paghahike", "backpacking",
      "paggugunita ng ibon", "paggugunita ng bituin",
      "pagtitipon", "pagtitipon ng selyo", "pagtitipon ng barya",
      "litratista", "videographer", "pagpapakandado ng drone",
      "laro ng board", "laro ng baraha", "puzzle", "sudoku",
      "laro ng video", "paglalaro sa PC", "paglalaro sa console",
      "pagbabasa", "nobela", "komiks", "manga", "magasin",
      "pagsusulat", "journaling", "tula", "pagba-blog",
      "sayaw", "awit", "pagtugtog ng instrumento", "DJing",
      "yoga", "pilates", "meditasyon",
      "skateboarding", "rock climbing",
      "langoy", "snorkeling", "kayaking", "canoeing", "rafting",
    ],
  },
  {
    id: "paaralan",
    name: "School",
    tagalog: "Paaralan",
    words: [
      "eskwela", "unibersidad", "kolehiyo", "klase",
      "silid-aralan", "aklatan", "laboratoryo", "gym", "kantina",
      "laruan", "hardin", "opisina",
      "guro", "propesor", "instructor", "direktor",
      "dean", "guidance counselor", "librarian", "tagalinis", "bantay",
      "estudyante", "kaklase", "kabatch",
      "paksa", "aralin", "module", "libro",
      "notebook", "panulat", "lapis", "eraser", "ruler",
      "kalkuladora", "computer", "laptop", "tablet", "proyektor",
      "chalk", "blackboard", "whiteboard", "marker",
      "pagsusulatan", "kuwiz", "recitation", "takdang-aralin",
      "proyektor", "pananaliksik", "tesis", "ulat",
      "marka", "skor", "honors", "cum laude",
      "graduasyon", "diploma", "sertipiko", "award", "medalya",
      "enrollment", "rehistrasyon", "matrikula", "scholarship", "baon",
      "recess", "break", "paalam", "bell", "flag ceremony",
      "scout", "club", "organisasyon",
      "batch", "section", "adviser",
    ],
  },
  {
    id: "panahon",
    name: "Weather & Nature",
    tagalog: "Panahon at Kalikasan",
    words: [
      "araw", "ulan", "kidlat", "kulog", "hangin",
      "bagyo", "habagat", "amihan", "tag-ulan",
      "tag-araw", "taglamig", "tag-init", "tagsibol", "taglagas",
      "hamog", "hamog na ulap",
      "bahaghari", "ulap", "langit",
      "dagat", "bundok", "bulkan",
      "ilog", "lawa", "dagat-dagatan",
      "gubat", "kweba",
      "niyebe", "yelo", "hamog",
      "baha", "lindol",
      "tsunami", "bagyo", "buwan",
      "talon", "alon", "coral", "damong dagat", "kapirasong shell",
      "bulaklak", "punongkahoy", "dahon", "ugat", "buto",
    ],
  },
  {
    id: "teknolohiya",
    name: "Technology",
    tagalog: "Teknolohiya",
    words: [
      "computer", "laptop", "desktop", "tablet", "smartphone",
      "Wi-Fi", "Bluetooth", "internet", "ethernet",
      "USB", "HDMI", "charger", "power bank",
      "baterya", "screen", "monitor", "keyboard", "mouse",
      "printer", "scanner", "webcam", "mikropono", "headphones",
      "earbuds", "speaker", "amplifier", "router", "modem",
      "hard drive", "SSD", "RAM", "processor",
      "server", "database", "software",
      "hardware", "app", "program", "browser", "website",
      "email", "spam", "virus", "malware",
      "AI", "artipisyal na intelihensiya", "robot", "drone",
      "laser", "VR", "virtual reality",
      "blockchain", "cryptocurrency", "Bitcoin",
      "gadget", "device", "tech", "imbento", "startup",
      "coding", "programming", "developer", "inhinyero", "hacker",
      "data", "analytics", "algorithm", "network", "cybersecurity",
    ],
  },
  {
    id: "pamilya",
    name: "Family",
    tagalog: "Pamilya",
    words: [
      "pamilya", "nanay", "tatay", "kuya",
      "ate", "bunso", "anak", "apo", "magulang",
      "lolo", "lola", "tito", "tita",
      "pinsan", "kapatid",
      "kambal", "baby", "bata",
      "tinedyer", "matanda",
      "asawa", "mister", "misis",
      "jowa", "kasintahan", "minamahal",
      "kasal", "hiwalay",
      "reunion", "salu-salo", "handaan", "pista", "kaarawan",
      "handaan ng kaarawan", "keyk", "kandila", "hiling", "ihip",
      "regalo", "sorpresa", "baso", "mga bula",
      "litrato", "album", "alaala",
      "tanghalian", "hapunan", "almusal", "merienda",
      "kamayan", "boodle fight",
      "picnic", "bakasyon", "paglalakbay",
      "camping", "pag-akyat sa bundok", "pakikipagsapalaran",
    ],
  },
  {
    id: "paligid",
    name: "Around the World",
    tagalog: "Sa Buong Mundo",
    words: [
      "Paris", "Eiffel Tower", "Pranses", "croissant",
      "London", "Big Ben", "Briton", "fish and chips",
      "New York", "Statue of Liberty", "Times Square", "Manhattan",
      "Tokyo", "Hapon", "sushi", "Mount Fuji",
      "Tsina", "Great Wall", "Tsino", "dim sum", "dragon",
      "India", "Taj Mahal", "curry", "yoga",
      "Australia", "Sydney Opera House", "kangaroo", "koala",
      "Egypt", "piramide", "sphinx", "pharaoh", "mummy",
      "Italy", "pizza", "pasta", "Rome", "Colosseum",
      "Brazil", "Carnival", "samba", "Amazon",
      "Mexico", "taco", "burrito", "piñata",
      "Germany", "Oktoberfest", "pretzel",
      "Korea", "K-pop", "Kimchi", "Korean BBQ", "BTS",
      "Thailand", "Thai food", "pad thai", "temple", "Bangkok",
      "Pilipinas", "Pinoy", "Pinay", "jeepney", "adobo",
      "Boracay", "Palawan", "Bohol", "Siargao", "Vigan",
      "Lechon", "Sinigang", "Kare-kare", "Jollibee", "balut",
    ],
  },
  {
    id: "kaswal",
    name: "Everyday Life",
    tagalog: "Pang-araw-araw",
    words: [
      "umaga", "tanghali", "gabi", "hapon", "madaling araw",
      "almusal", "tanghalian", "hapunan", "merienda",
      "tulog", "gising", "pangarap", "bangungot",
      "sapatos", "damit", "sando", "shorts", "pantalon",
      "suweter", "dyaket", "kotse", "sombrero", "takip",
      "bag", "wallet", "telepono", "sunglasses",
      "payong", "raincoat", "botas",
      "sipilyo", "pastilya ng ngipin", "sabon", "shampoo",
      "tuwalya", "salamin", "suklay", "sipilyo",
      "sabon", "detergent", "pampalambot", "pampaputi", "plantsa",
      "mashingina", "vacuum", "walis", "walis tingting",
      "plato", "kutsara", "tinidor", "kutsilyo", "baso",
      "kusina", "refrigerator", "hurno", "microwave", "toaster",
      "electric fan", "aircon", "heater", "lampara",
      "telebisyon", "remote", "sopa", "mesa",
      "upuan", "kama", "unan", "kumot", "mattress",
      "orasan", "alarm clock", "relo", "kalendaryo",
    ],
  },
  {
    id: "kendi",
    name: "Sweets & Drinks",
    tagalog: "Kendi at Inumin",
    words: [
      "kendi", "tsokolate", "gummy bear",
      "lollipop", "bubble gum", "chewing gum",
      "marshmallow", "jelly bean",
      "cookies", "biskwit", "crackers", "chips",
      "keyk", "cupcake", "brownie", "muffin", "donut",
      "ice cream", "gelato", "sorbet", "froyo", "popsicle",
      "halo-halo", "scramble", "dirty ice cream",
      "kape", "latte", "cappuccino", "espresso",
      "frappe", "mocha", "americano", "macchiato",
      "tsaa", "milk tea", "boba", "bubble tea",
      "smoothie", "shake", "jus", "lemonade",
      "soda", "Coke", "Pepsi", "Sprite",
      "energy drink", "Gatorade", "Powerade",
      "tubig", "mineral water",
      "serbesa", "craft beer",
      "alak", "red wine", "white wine", "champagne",
      "cocktail", "margarita", "mojito", "mimosa", "sangria",
    ],
  },
  {
    id: "disenyong",
    name: "Art & Design",
    tagalog: "Sining at Disenyo",
    words: [
      "pagpipinta", "pagdrowing", "eskultura", "palayok", "keramika",
      "litrato", "paggawa ng pelikula", "arkitektura", "interior design",
      "graphic design", "web design", "fashion design",
      "kulay", "pula", "asul", "berde",
      "dilaw", "kahel", "lila", "rosas", "itim",
      "puti", "kulay-abo", "kahel", "ginto", "pilak",
      "anyo", "hugis", "guhit", "teksto", "lugar",
      "perspektibo", "proportion", "balanse", "kontrasto", "armoniya",
      "simetriya", "asimetriya", "pamamaraan", "ritmo", "galaw",
      "oil paint", "watercolor", "acrylic", "pastel", "charcoal",
      "tinta", "lapis", "sipilyo", "palette", "easel",
      "kuwadro", "sketchbook", "papel", "tablet",
      "galeriya", "museo", "exhibit", "auction", "studio",
      "masterpiece", "abstrak", "realismo", "surrealism", "impresyonismo",
      "pop art", "street art", "graffiti", "mural", "poster",
      "logo", "brand", "tipograpiya", "font", "layout",
    ],
  },
];
